config/routes.rb
C4cMarketing::Application.routes.draw do

  root 'home#index'
  get 'how_it_works' => 'home#how_it_works', :as => :how_it_works
  get 'case_studies' => 'home#case_studies', :as => :case_studies
  get 'about_us' => 'home#about_us', :as => :about_us

  resources :enquiries, :only => :create

end

app/models/enquiry.rb
# == Schema Information
#
# Table name: enquiries
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  phone      :string(255)
#  email      :string(255)
#  blog_url   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Enquiry < ActiveRecord::Base
  validates_presence_of :email, :name, :blog_url
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  validate :blog_url_validation

  def blog_url_validation
    begin
      uri = URI.parse(self.blog_url)
      self.errors.add(:blog_url, 'Invalid Blog Url') unless ((uri.kind_of?(URI::HTTP)) || (uri.kind_of?(URI::HTTPS)))
    rescue => e
      Rails.logger.debug("#{e.message} \n #{e.backtrace}")
      self.errors.add(:blog_url, 'Invalid Blog Url')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  def create
    @enquiry = Enquiry.new(:name => params[:FirstName],
                           :email => params[:Email],
                           :blog_url => params[:BlogUrl],
                           :phone => params[:phone]

                          )

    if Enquiry.where(:email => @enquiry.email).exists?
      render :json => {:request_status => :success}, :status => :ok
    else
      if @enquiry.save
        Notifier.new_enquiry_mail(@enquiry).deliver
        render :json => {:request_status => :success}, :status => :ok
      else
        render :json => {:request_status => :failure}, :status => :ok
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def how_it_works
        
    end
    def case_studies
        
    end
    def about_us
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/enquiries/create.html.erb
<h1>Enquiries#create</h1>
<p>Find me in app/views/enquiries/create.html.erb</p>

app/views/home/about_us.html.erb
<section id="masthead">
    <div class="wrapper clearfix">
        <div id="masthead-content">
            <h1>About us</h1>
            <p>We faced the problem. Hence we went ahead and solved it for ourselves.</p>
			<br/>
			<%= render :partial => 'partials/twitter_callout'%>
        </div>
    </div>
</section>
<section class="container" class="clearfix">
    <div class="wrapper clearfix">
        <div id="our-story">
            <h2>OUR STORY</h2>
            <p>We started our journey on the belief that every single piece of authentic content,
              deserves attention from those who it was written for. You are not Seth Godin, but that does not mean your voice should not be heard.
              We want your content to reach out to people who are talking around it right now.
            </p>
			<br/>
             <p>We’re here to help people who write genuine content. Before we define what we mean by genuine content,
              let us describe what genuine content is not.
            </p>
        </div>
    </div>
</section>
<section class="container" id="genuine-content">
    <div class="wrapper clearfix">
        <div id="add-content">
            <h3>Your content is not genuine if;</h3>
            <p>Your primary goal is to benefit your business.</p>
			<br/>
            <ol type="1">
				<li>Your only aim is to sell.</li>
				<li>Your content is Stuffed with keywords.</li>
				<li>Your content is not written to be truly useful.</li>
			</ol>
        </div>
    </div><!--wrapper-->
</section>
<section class="container" class="clearfix">
    <div class="wrapper clearfix">
        <div id="our-story">
            <h2>HOW DID IT START?</h2>
            <p>As part of Inbound marketing for our company Idyllic Software, we produced truly authentic content.
              However we quickly realized that our content was not reaching those whom it was written for.
              Hence we bid adieu to our Inbound Marketing tool with this <a target='_blank' href='http://www.google.com/url?q=http%3A%2F%2Fblog.idyllic-software.com%2Fwhy-did-i-quit-on-hubspot%2F&sa=D&sntz=1&usg=AFQjCNGUrtE-d0Q19SPefkIRhQjK3_Mx2g'>
              final word </a> and embarked on the journey to build C4C
            </p>
        </div>
    </div>
</section>
    <%= render partial: "partials/profile"%>
        </div>
    </div>
</section>
<section id="get-started">
    <!-- <img src="" alt="Random"> -->
    <div class="form" ng-app="app" ng-controller="FormController">
        <strong>Contact us</strong>
        <p>Have queries? Contact our marketing team. We promise we will not sell or<br> share your information.</p>
        <%= render partial: "partials/contactform" %>
    </div>
</section>

app/views/home/case_studies.html.erb
<section id="masthead">
    <div class="wrapper clearfix">
        <div id="masthead-content">
            <h1>Case Studies</h1>
			<p>Enough talking. See it for yourself from here on.</p>
			<br/>
			<%= render :partial => 'partials/twitter_callout'%>
        </div>
    </div>
</section>
<section class="container">
    <div class="wrapper clearfix">
        <div class="case-study" style='display:block'>
            <h2>@SAALON</h2>
            <h3>We made Eric stick to Mongodb, just when he was about to quit on it.</h3>
            <p>All we did was found his conversation with his friend and sent him a blog that we wrote.</p>
            <div class="placeholder" style='border:2px solid #d6dfe6;height:490px'>
              <%= image_tag 'Mongo.png' %>
            </div>
        </div>
        <hr>
		<div class="case-study">
            <h2>@BradFeld</h2>
            <h3>We sold a book for Brad Feld.</h3>
            <p>This is when the opportunity meets preparation. C4C put us there when the discussion was happening.</p>
            <div class="placeholder" style='height:422px;'>
              <%= image_tag 'BradFeld.png' %>
            </div>
        </div>
		<hr/>
        <div class="case-study">
            <h2>@ATT</h2>
            <h3>We sent an exhausted visitor to the ATT teleportation lounge in SxSW.</h3>
            <p>Once again it was just as easy. Though we weren't successful at being grammatically correct.</p>
            <div class="placeholder" style='height:541px;'>
              <%= image_tag 'att.png' %>
            </div>
        </div>
        <hr/>
		<div class="case-study">
            <h2>@NTTcom</h2>
            <h3>Marc Andreessen favorited our tweet.</h3>
            <p>C4C got the discussion around marc's investment in digital ocean. We chimed in.</p>
            <div class="placeholder" style='height:102px;'>
              <%= image_tag 'marc.png' %>
            </div>
        </div>
		<hr/>
	
		<div class="case-study">
            <h2>@idyllicsoftware</h2>
            <h3>Got our article cross referenced in a publishing.</h3>
            <p>We got our article written long time ago into the lime light again.</p>
            <div class="placeholder" style='height:360px;'>
              <%= image_tag 'article.png' %>
            </div>
        </div>
    </div>
</section>
<section id="get-started">
    <!-- <img src="" alt="Random"> -->
    <div class="form" ng-app="app" ng-controller="FormController">
        <strong>Want to get started?<sup>BETA</sup></strong>
        <p>We're being selective of our customers at the moment.<br>We are looking for genuine, high quality business blogs to start with. Do you have one?<br>Awesome. Tell us about yourself. We'll get in touch with your ASAP.</p>
        <%= render partial: "partials/get_started" %>
    </div>
</section>

app/views/home/how_it_works.html.erb
<section id="masthead">
    <div class="wrapper clearfix">
        <video id="video">
        Sorry, your browser doesn't support embedded videos, 
        but don't worry, you can <a href="videofile.ogg">download it</a>
        and watch it with your favorite video player!
        </video>
        <div id="masthead-content">
            <h1>Write. Listen. Talk.</h1>
            <p>Yup, it's that simple. As long as you write good content, we'll bring in right converations.<br>Pellentesque habitant morbi tristique senectus et netus et malesuada<br>egestas. Pellentesque habitant morbi</p>
        </div>
    </div>
</section>
<section class="container">
    <div class="wrapper clearfix">
        <h2>ONCE YOU SIGN UP</h2>
        <h3>We make it as easy as possible to get you right conversations.</h3>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada<br>egestas. Pellentesque habitant morbi</p>
        <section id="steps" class="clearfix">
            <div class="step">
                <img src="" alt="Step 1">
                <span class="number">1</span>
                <strong>IMPORT YOUR BLOG</strong>
                <p>Pellentesque et netus et malesuada fames ac turpis egestas.</p>
            </div>
            <div class="step">
                <img src="" alt="Step 2">
                <span class="number">2</span>
                <strong>CONFIGURE KEYWORDS</strong>
                <p>Pellentesque et netus et malesuada fames ac turpis egestas.</p>
            </div>
            <div class="step">
                <img src="" alt="Step 3">
                <span class="number">3</span>
                <strong>WE FIND TWITTER CONVERSATIONS</strong>
                <p>Pellentesque et netus et malesuada fames ac turpis egestas.</p>
            </div>
            <div class="step">
                <img src="" alt="Step 3">
                <span class="number">4</span>
                <strong>NEW CONVERSATIONS ARE NOTIFIED</strong>
                <p>Pellentesque et netus et malesuada fames ac turpis egestas.</p>
            </div>
        </section>
    </div>
</section>
<section id="get-started">
    <img src="" alt="Random">
    <div class="form" ng-app="app" ng-controller="FormController">
        <strong>Want to get started?<sup>BETA</sup></strong>
        <p>We're being selective of our customers at the moment.<br>We are looking for genuine, high quality business blogs to start with. Do you have one?<br>Awesome. Tell us about yourself. We'll get in touch with your ASAP.</p>
        <%= render partial: "partials/get_started" %>
    </div>
</section>

app/views/home/index.html.erb
<section id="masthead">
    <div class="wrapper clearfix">
        <div id="masthead-content" style='float:right; width:48%'>
            <h1 class="pageTitle" style="font-size: 35px; line-height: 40px;">Discover & engage with new potential customers on twitter.</h1>
            <p> &nbsp; </p>
            <p style="line-height: 25px;">Proactively reach your potential customers before they reach you or your competition. Engage with them while they are discussing it on twitter.</p>
			<br/>
			<%= render :partial => 'partials/twitter_callout'%>
        </div>
	  <iframe src="//player.vimeo.com/video/98027222" width="500" height="281" frameborder="0" style="-moz-box-shadow: 4px 4px 14px #000; -webkit-box-shadow: 4px 4px 14px #000;box-shadow: 4px 4px 14px #000;" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
</section>
<section class="container">
    <div class="wrapper clearfix">
        <h2>CONVERSATIONS FOR CONTENT</h2>
        <h3>Why choose C4C?</h3>
        <p>Enable your blogs to listen to discussions on twitter.
          Take your content to interested people.</p>
        <section id="reasons" class="clearfix">
            <div class="reason">
                <!--<img src="" alt="Reason 1">-->
                <strong>THE PROBLEM</strong>
                <p>Your blog is not reaching the right audience.</p>
            </div>
            <div class="reason">
                <!--<img src="" alt="Reason 2">-->
                <strong>THE GAP</strong>
                <p>People are already discussing that topic on twitter. They are your true audience. But there is no way to reach them.</p>
            </div>
            <div class="reason">
                <!--<img src="" alt="Reason 3">-->
                <strong>THE SOLUTION - C4C</strong>
                <p>Find those conversations as they happen and engage.</p>
            </div>
        </section>
        <span class="time-taken">That's exactly what I wanted</span>
        <a href="#get-started" class="sign-up-link">SIGN UP TODAY</a>
    </div>
</section>
<section id="banner">
    <span id="conversation" class="chat-icon entypo-comment"></span>
    <strong>Your content has one mission - Conversations</strong>
    <p>We'll get you those real discussions. Chime in if you deem fit.</p>
</section>
<section id="get-started">
    <div class="form" ng-app="app" ng-controller="FormController" style='width:100%;'>
        <strong>Want to get started?<sup>BETA</sup></strong>
        <p>We're being selective of our customers at the moment.<br>We are looking for genuine, high quality business blogs to start with. Do you have one?<br>Awesome. Tell us about yourself. We'll get in touch with you ASAP.</p>
        <%= render partial: "partials/get_started" %>
    </div>
</section>

<%= render :partial => 'partials/thank_you' %>
<%= render :partial => 'partials/awkward_moment' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Conversations for your blog articles.</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link href='http://fonts.googleapis.com/css?family=Signika:400,600,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="http://weloveiconfonts.com/api/?family=entypo">
    <%= csrf_meta_tags %>
</head>
<body id="<%= params[:action]%>">
    <%= render partial: "partials/header" %>
    <%= yield %>
    <%= render partial: "partials/footer" %>
	<%= render partial: "partials/ga" %>
</body>
</html>

app/views/notifier/new_enquiry_mail.html.erb
<html>
    <head></head>
    <body>
        <p> Hello Sacred Admins of C4CHQ, </p>

        <p> A new enquiry has come in from <%= @enquiry.name %> <br>
          Email: <%= @enquiry.email %> <br/>
          Blog Url: <%= @enquiry.blog_url %> <br/>
          Phone: <%= @enquiry.phone.to_s %>
        </p>
    </body>
</html>

app/views/partials/_awkward_moment.html.erb
<section id='awkward-moment' style='display:none;'>
  <div class='form'>
    <strong>
      Woops! Looks like you caught us in an awkward moment.
    </strong>

    <p>
      We are glad that this interests you. Give us a moment to fix what we screwed up.
      <br/>
      We'd love it if you could try again in a few minutes.
    </p>
  </div>
</section>

app/views/partials/_contactform.html.erb
<form id="contact-form" name="ContactForm" class="getstartedform clearfix" novalidate>
    <span ng-show="ContactForm.FirstName.$error.required && !ContactForm.FirstName.$pristine">Please enter first name</span>

    <input type="text" class="vertical-guttter" name="FirstName" id="firstName" placeholder="First Name" ng-model="First.Name" required>
    <input type="text" class="vertical-guttter" id="phone" placeholder="Phone # (optional)">

    <span ng-show="ContactForm.Email.$error.required && !ContactForm.Email.$pristine">Please enter email</span>
    <span ng-show="ContactForm.Email.$error.email && !ContactForm.Email.$pristine">Please enter valid email</span>

    <input type="email" name="Email" id="email" class="vertical-guttter" placeholder="Email Address" ng-model="Email" required>

    <span ng-show="ContactForm.BlogUrl.$error.required && !ContactForm.BlogUrl.$pristine">Please enter url</span>
    <span ng-show="ContactForm.BlogUrl.$error.url && !ContactForm.BlogUrl.$pristine">Please enter valid url</span>
    <span ng-show="ContactForm.PurposeConnection.$error.required && !ContactForm.PurposeConnection.$pristine">Please enter purpose of connecting</span>
    
    <input type="text" name="PurposeConnection" class="vertical-guttter" ng-model="Purpose.Connection" placeholder="Purpose of Connecting" required>
    <input type="submit" value="SUBMIT" id="submitBtn" ng-disabled="ContactForm.$invalid">
</form>

app/views/partials/_footer.html.erb
<footer id="footer" style='margin-top:-4em;'>
    <div id="footerWrapper" class="wrapper clearfix">
        <nav class="footerBlock" id="footerNav">
            <strong>C4C</strong>
            <a href="<%= case_studies_url %>">Case studies</a>
            <a href="<%= about_us_url %>">About us</a>
        </nav>
        <div id="copyright">
			<%= render :partial => 'partials/twitter_callout'%>
            <p>&copy; 2014 C4C All rights reserved.</p>
        </div>
    </div>
</footer>

app/views/partials/_ga.html.erb
<% if Rails.env.production? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45590054-2', 'c4chq.com');
  ga('send', 'pageview');

</script>
<% end %>

app/views/partials/_get_started.html.erb
<form action='/enquiries' id="sign-up-form" name="SignUpForm" class="contactform clearfix" ng-submit="submitForm(SignUpForm.$valid)" novalidate>
    <span ng-show="SignUpForm.FirstName.$error.required && !SignUpForm.FirstName.$pristine">Please enter first name</span>

    <input type="text" class="vertical-guttter" name="FirstName" id="firstName" placeholder="First Name" ng-model="First.Name" required>
    <input type="text" class="vertical-guttter" id="phone" name='phone' placeholder="Phone # (optional)">

    <span ng-show="SignUpForm.Email.$error.required && !SignUpForm.Email.$pristine">Please enter email</span>
    <span ng-show="SignUpForm.Email.$error.email && !SignUpForm.Email.$pristine">Please enter valid email</span>

    <input type="email" name="Email" id="email" class="vertical-guttter" placeholder="Email Address" ng-model="Email" required>

    <span ng-show="SignUpForm.BlogUrl.$error.required && !SignUpForm.BlogUrl.$pristine">Please enter url</span>
    <span ng-show="SignUpForm.BlogUrl.$error.url && !SignUpForm.BlogUrl.$pristine">Please enter valid url</span>

    <input type="url" id="blogUrl" name="BlogUrl" class="vertical-guttter" placeholder="Blog (Ex: http://example.com)" ng-model="Blog.Url" required>
    <input type="submit" value="SUBMIT" id="submitBtn" ng-disabled="SignUpForm.$invalid">
</form>

app/views/partials/_header.html.erb
<header id="header" class="clearfix">            
    <section id="top-links">
        <span class="ask">Your content has one mission</span>
        <a href="#get-started" class="sign-up-link">Conversations</a>
    </section>
    <section id="left-head">
        <a id="logo" href="/">C4C</a>
        <nav id="primary-nav">
            <!--<a href="/how_it_works">How it works</a>-->
            <a href="/case_studies">Case studies</a>
            <a href="/about_us">About us</a>
			<a href="http://talk.c4chq.com" target="blank">Blog</a>
        </nav>
    </section>
</header>

app/views/partials/_profile.html.erb
<div id="profiles" class="clearfix">
    <div class="wrapper clearfix">
		<div class="profile">
            <div class="profileInfo pull-right">
                <strong>Siddharth Ravichandran</strong>
				<span>Chief Technology Officer</span>
                <p>Sid is our rock solid polyglot programmer. He is fast, witty and believes in keeping it simple. He is a voracious reader and pretty much knows everything that is happening in the tech world. Sid has his Master’s degree in computer science from Oxford Brookes University, UK.
				</p>
                <div class="clearfix">
                    <a href="https://twitter.com/super_sid" class="icon entypo-twitter">super_sid</a>
					<a class="web-url" href="http://siddharth-ravichandran.com/">My blog</a>
                </div>
            </div>
            <div class="photo pull-left">
                <%=image_tag 'siddharth.png'%>
            </div>
        </div>
	  </div>
	
	<hr/>
		
		<div class="wrapper clearfix">
		<div class="profile">
	            <div class="profileInfo pull-left">
	                <strong>Amar Daxini</strong>
					<span>Lead Architect</span>
	                <p>Amar is a rockstar Ruby on Rails programmer. His entrepreneurial spirits and leadership qualities get's him very well connected in the tech world locally. At times, we wonder if he is a recruiter or a developer. Nonetheless, he is awesome.</p>
	                <div class="clearfix">
	                    <a href="in.linkedin.com/in/amardaxini" class="icon entypo-linkedin"></a>
						<a class="icon entypo-github" href="https://github.com/amardaxini">Github</a>
	                </div>
	            </div>
	            <div class="photo pull-right">
	                <%=image_tag 'amar.png'%>
	            </div>
		</div>
		</div>
		
			<hr/>
		
		<div class="wrapper clearfix">
		<div class="profile">
            <div class="profileInfo pull-right">
                <strong>Abhijit Rao</strong>
				<span>Challenge Seeker</span>
                <p>
					Abhijit is our all rounder who has been seeking true challenges. He single handedly built the product and team for Indian version of Kayak named Cleartrip. He is the man behind the fastest algorithm that brings you the cheapest fares and best options. He was also the key contributor on the cleartrip UX team. He is a rare developer with a very keen eye on UX.				
				</p>
                <div class="clearfix">
                    <a class="icon entypo-github" href="https://github.com/quasi">Github</a>
					<a class="web-url" href="http://quasilabs.com/">My website</a>
                </div>
            </div>
            <div class="photo pull-left">
                <%=image_tag 'Abhijit.jpg'%>
            </div>
        </div>
		</div>
		
			<hr/>

		<div class="wrapper clearfix">
		<div class="profile">
	            <div class="profileInfo pull-left">
	                <strong>Vinod Sobale</strong>
					<span>Front End specialist</span>
	                <p>Vinod specializes in the front end development. He is very strongly and most times rightly opinionated about how front end should be developed. He likes to write on <a href="http://vinodsobale.com/">vinodsobale.com</a><!--  Recently he put up a contradicting post on <a href="http://blog.idyllic-software.com/why-we-dont-use-twitter-bootstrap/" target="blank">Why We Do Not Use Twitter Bootstrap.</a> --> He is proud of the framework that he developed. 
					</p>
	                <div class="clearfix">
	                    <a href="in.linkedin.com/in/vinodsobale" class="icon entypo-linkedin"></a> 
						<a class="icon entypo-github" href="https://github.com/vinu123/zunka">Zunka-SAAS</a> 
						<a class="icon entypo-github" href="https://github.com/vinu123/zunkaless">Zunkales</a> 
						<a class="web-url" href="http://vinodsobale.com/">My Website</a>
	                </div>
	            </div>
	            <div class="photo pull-right">
	                <%=image_tag 'vinod.jpg'%>
	            </div>
		</div>
		</div>
		
			<hr/>
		
		
		<div class="wrapper clearfix">
		<div class="profile">
            <div class="profileInfo pull-right">
                <strong>Sachin Gavas</strong>
				<span>User Experience Specialist</span>
                <p>
					The easiest way to learn about the designer is by seeing his designs. Click on his below profiles to know his work.
				</p>
                <div class="clearfix">
                    <a class="icon entypo-pinterest" href="http://www.pinterest.com/sachingawas/portfolio/">ortfolio</a>
					<a class="web-url" href="http://iamsach.in/">My website</a>

                </div>
            </div>
            <div class="photo pull-left">
                <%=image_tag 'sachin.jpg'%>
            </div>
        </div>
		</div>
		
			<hr/>
		
			<div class="wrapper clearfix">
			<div class="profile">
		            <div class="profileInfo pull-left">
		                <strong>Jinesh Parekh</strong>
						<span>Chief Executive Officer</span>
		                <p>Jinesh is a conscious entrepreneur. He is the founder of Idyllic Software - A niche Ruby on rails boutique. He has written a lot of code as a software developer in his past life. He builds businesses for the problems he cannot find a solution for. That is exactly how C4C also came into existence. For him money is the need of the hour, but not the purpose of life.
						</p>
		                <div class="clearfix">
		                    <a href="http://www.linkedin.com/in/rubyonrailswithidyllicsoftware" class="icon entypo-linkedin"></a>  
		<a href="https://twitter.com/idyllicsoftware" class="icon entypo-twitter">idyllicsoftware</a>  
							<a class="web-url" href="http://www.idyllic-software.com/">Idyllic Software</a>
		                </div>
		            </div>
		            <div class="photo pull-right">
		                <%=image_tag 'jinesh.jpg'%>
		            </div>
			</div>
			</div>
			
				<hr/>
</div>

app/views/partials/_thank_you.html.erb
<section id='thank-you' style='display:none;'>
  <div class='form'>
    <strong>
      Thank you for your interest.
    </strong>

    <p>
      We're excited that this interests you.
      <br/>
      We'll reach out to you shortly and let you know when our early access will be available to you.
    </p>
  </div>
</section>

app/views/partials/_twitter_callout.html.erb
<a href="https://twitter.com/__conversation_" class="icon entypo-twitter twitter_callout" target="blank">&nbsp;Follow us</a>